# Copyright 2021-2023 Nordcloud Oy or its affiliates. All Rights Reserved.

name: Pull Request Size
on: [pull_request]

jobs:
  labeler:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    name: Label the PR size
    steps:
      - uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: size/xs
          xs_max_size: '20'
          s_label: size/s
          s_max_size: '100'
          m_label: size/m
          m_max_size: '400'
          l_label: size/l
          l_max_size: '800'
          xl_label: size/xl
          fail_if_xl: 'false'
          message_if_xl: ''
          files_to_ignore: package-lock.json
